sudo: required

services:
    - docker


before_install:
    - docker build -t reply2anish/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true reply2anish/docker-react npm run test